version: "3.5"

services:
  mysql-db:
    image: arm64v8/mysql:8.0
    ports:
      - 3306:3306
    environment:
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: definitions
      MYSQL_PORT: 3306

    volumes:
      - ./database:/docker-entrypoint-initdb.d:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

  app:
    image: dashboard:latest
    container_name: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      # - "3306:3306"
    networks:
      - spring-boot-app
    environment:
      MYSQL_HOST: docker.for.mac.host.internal

  api:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

networks:
  spring-boot-app:
