services:
  backend:
    container_name: dashboard
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - spring-app
    expose:
      - "8080"

  database:
    image: mysql:8.4.2
    container_name: mysql_database
    privileged: true
    environment:
      MYSQL_DATABASE: "definitions"
      MYSQL_ROOT_PASSWORD: "test123"
    ports:
      - "3306:3306"
    volumes:
      - "./database/01-initial-db.sql:/docker-entrypoint-initdb.d/default_data.sql:ro"
    #      - "./database/data:/var/lib/mysql"
    networks:
      - spring-app
    healthcheck:
      test: ["CMD-SHELL", "mysql -ptest123 -e 'select 1'"]
      interval: 5s
      retries: 50

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - spring-app
    depends_on:
      backend:
        condition: service_started

networks:
  spring-app:
